### ISSUE TITLE
rosdep libftdipp-dev not resolving properly for Ubuntu 16.04

### ISSUE THREAD

**Issue by koenlek** [ros/rosdistro#11626]
It tries to install "libftdipp-dev" but I think it should be "libftdipp1-dev" on xenial. Should the rosdep in https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml
be updated from this:

```
libftdipp-dev:
  fedora: [libftdi-c++-devel]
  ubuntu: [libftdipp-dev]
```

To e.g. this:

```
libftdipp-dev:
  fedora: [libftdi-c++-devel]
  ubuntu: 
    precise: [libftdipp-dev]
    trusty: [libftdipp-dev]
    vivid: [libftdipp-dev]
    wily: [libftdipp-dev]
    xenial: [libftdipp1-dev]
```
