### ISSUE TITLE
libglew-dev for Ubuntu 16.04 Xenial Xerus

### ISSUE THREAD

**Issue by Yelen719** [ros/rosdistro#11717]
In order to install GLEW library on Ubuntu 16.04 Xenial Xerus with rosdep, the libglew-dev section in https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml should be updated to:

```
libglew-dev:
  arch: [glew]
  debian: [libglew-dev]
  fedora: [glew-devel]
  gentoo:
    portage:
      packages: [media-libs/glew]
  ubuntu:
    oneiric: [libglew1.5-dev]
    precise: [libglew1.6-dev]
    quantal: [libglew-dev]
    raring: [libglew-dev]
    saucy: [libglew-dev]
    trusty: [libglew-dev]
    utopic: [libglew-dev]
    vivid: [libglew-dev]
    xenial: [libglew-dev]
```

reference: https://launchpad.net/ubuntu/xenial/+package/libglew-dev
