### ISSUE TITLE
Help needed to manage a major package reorg.

### ISSUE THREAD

**Issue by dustingooding** [ros/rosdistro#12528]
I'm the new maintainer for the Robonat2 Gazebo simulation and all the related packages that it needs.  We've got new package names, new package repositories, new package metadata, etc.  Old repositories are deprecated and should not be used.

I don't expect the ROS build farm to generate debs from this new codebase, but I do want the ROS wiki to display the most-current information.

Can I get some guidance on where to start?  I'm very new to this.  @scpeters sent me here.

Here's a listing of the new repos and their locations (vcs export).  https://gitlab.com/nasa-jsc-robotics/r2_workspaces/blob/develop/public_sim.yaml

```
repositories:
    fsm_utils:
        type: git
        url: git@gitlab.com:nasa-jsc-robotics/fsm_utils.git
    hayai:
        type: git
        url: git@gitlab.com:nasa-jsc-robotics/hayai.git
    iss_taskboard_gazebo:
        type: git
        url: git@gitlab.com:nasa-jsc-robotics/iss_taskboard_gazebo.git
    nasa_common_cmake:
        type: git
        url: git@gitlab.com:nasa-jsc-robotics/nasa_common_cmake.git
    nasa_common_logging:
        type: git
        url: git@gitlab.com:nasa-jsc-robotics/nasa_common_logging.git
    r2_description:
        type: git
        url: git@gitlab.com:nasa-jsc-robotics/r2_description.git
    r2_gazebo:
        type: git
        url: git@gitlab.com:nasa-jsc-robotics/r2_gazebo.git
    r2_gazebo_gripper:
        type: git
        url: git@gitlab.com:nasa-jsc-robotics/r2_gazebo_gripper.git
    r2_gazebo_interface:
        type: git
        url: git@gitlab.com:nasa-jsc-robotics/r2_gazebo_interface.git
    r2_moveit_config:
        type: git
        url: git@gitlab.com:nasa-jsc-robotics/r2_moveit_config.git
    r2_msgs:
        type: git
        url: git@gitlab.com:nasa-jsc-robotics/r2_msgs.git
    r2_supervisors_control:
        type: git
        url: git@gitlab.com:nasa-jsc-robotics/r2_supervisors_control.git
    r2_upperbody_moveit_config:
        type: git
        url: git@gitlab.com:nasa-jsc-robotics/r2_upperbody_moveit_config.git
    robodyn_controllers:
        type: git
        url: git@gitlab.com:nasa-jsc-robotics/robodyn_controllers.git
    robodyn_mechanisms:
        type: git
        url: git@gitlab.com:nasa-jsc-robotics/robodyn_mechanisms.git
    robodyn_ros:
        type: git
        url: git@gitlab.com:nasa-jsc-robotics/robodyn_ros.git
    robodyn_utilities:
        type: git
        url: git@gitlab.com:nasa-jsc-robotics/robodyn_utilities.git
    robot_instance:
        type: git
        url: git@gitlab.com:nasa-jsc-robotics/robot_instance.git
```
