### ISSUE TITLE
Is ros2_canopen available or not in ROS2 humble

### ISSUE THREAD

**Issue by ghanim-mukhtar** [ros/rosdistro#40448]
Hello there,

I see in `humble/distribution.yaml` [here](https://github.com/ros/rosdistro/blob/master/humble/distribution.yaml#L6763C1-L6763C3) that `ros2_canopen` is listed: 
```
ros2_canopen:
    doc:
      type: git
      url: https://github.com/ros-industrial/ros2_canopen.git
      version: humble
    source:
      type: git
      url: https://github.com/ros-industrial/ros2_canopen.git
      version: humble
    status: developed
```
But practically when I try to install it with `sudo apt install ros-humble-ros2-canopen` I cannot find it.

# Environment:

- Linux ubuntu 22.04 jammy
- Tested under both architecture: AMD64 and ARM64 both not working

# Step to reproduce:

1. Create a ROS2 package where in the `package.xml` you should add: `<depend>ros2_canopen</depend>`
2. Then `sudo apt update`
3. After `rosdep update`
4. Finally `rosdep install --from-path src --ignore-src -yr`

# Expected behavior:
Everything install correctly

# Actual behavior:
I got this on the ARM64: 

```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
delta_ros2_canopen: Cannot locate rosdep definition for [ros2_canopen]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully
```

# Other info
I see this closed issue #11567 due to inactivity and maybe it is related to it and the debians have never been produced ?
