### ISSUE TITLE
Question: rosdep yaml consistency

### ISSUE THREAD

**Issue by jbohren** [ros/rosdistro#7148]
So I wanted to make it so [rosindex](rosindex.github.io) can **(1)** determine if a package dependency is a rosdep or if it's another ROS package. Additionally, I wanted to **(2)** show a page listing the details of that rosdep (i.e. which platforms it's available on and which distributions). In the future, this could be used to **(3)** automatically declare whether a given package is supported on a given platform.

1. Is possible just by reading the identifiers in the rosdep yaml files, which is fine
2. Creates some issues though, because of the variability in the way rosdep keys are listed. I've found that the following forms exist in the current yaml files:

    ```yaml
#### CASE A ####

ROSDEPKEY:
  PLATFORM: array-of-deps

#### CASE B ####

ROSDEPKEY:
  PLATFORM:
    VERSION: array-of-deps

#### CASE C ####

ROSDEPKEY:
  PLATFORM:
    VERSION:
      MANAGER: array-of-deps

#### CASE D ####

ROSDEPKEY:
  PLATFORM:
    VERSION:
      MANAGER:
        packages: array-of-deps

#### CASE E... ugh ####

ROSDEPKEY:
  PLATFORM:
    MANAGER:
      packages: array-of-deps

#### CASE FFFF... ugh ####

ROSDEPKEY:
  PLATFORM:
    VERSION:
      packages: array-of-deps 
```

    Without knowing the names of the platforms, platform versions, and package managers a priori, case *E* and case *FFFF* are indistinguishable. Are such keys correct, or is one of these cases wrong? I understand that in most cases, the only rosdep keys you care about in a given instance are the ones needed by your OS, in which case you know what platform/version/etc you're looking for.

3. Is further out but a good thing to have on the horizon, I think.
