### ISSUE TITLE
rosdep: bad rule for python-pymodbus in python.yaml 

### ISSUE THREAD

**Issue by jbohren** [ros/rosdistro#7151]
What's going on here (`debian: precise`): https://github.com/ros/rosdistro/blob/master/rosdep/python.yaml#L951

Added in: https://github.com/ros/rosdistro/commit/453b138b5bc1da7a6972dd398a75998d0cb09e05

```yaml
python-pymodbus:
  debian:
    precise: [python-pymodbus]
  fedora: [pymodbus]
  ubuntu:
    precise: [python-pymodbus]
    raring: [python-pymodbus]
    saucy: [python-pymodbus]
    trusty: [python-pymodbus]
```
